/* The complete-set sheets in assets/icon-atlas/sets, registered as selectable
   icon sets. Vite emits each sheet as its own asset URL, so a sheet is only
   fetched once a tile actually paints from it — importing this module costs
   nothing until a player picks one of these sets.

   Sheets are generated by scripts/generate-icon-set-atlases.mjs and named after
   the built-in set they depict; a set with no sheet on disk simply contributes
   nothing here. */
import { ATLAS_LAYOUT, ICON_SET_MANIFEST, atlasSlots, registerIconSets } from './iconSets.js';

const sheets = import.meta.glob('../assets/icon-atlas/sets/*.{webp,svg}', {
  eager: true, query: '?url', import: 'default',
});
const byFilename = Object.fromEntries(Object.entries(sheets).map(([path, url]) =>
  [path.slice(path.lastIndexOf('/') + 1), url]));

const slots = atlasSlots('all');

const generatedSets = ICON_SET_MANIFEST.flatMap(([base, label]) => {
  const data = byFilename[`${base}-icon-atlas.webp`];
  if (!data) return [];
  const id = `atlas-${base}`;
  return [[id, {
    id, label: `${label} (atlas)`, base,
    icons: Object.fromEntries(slots.map((slot, index) => [`${slot.domain}:${slot.key}`, `atlas:${id}:${index}`])),
    atlas: {
      data, mime: 'image/webp', group: 'all', count: slots.length,
      columns: ATLAS_LAYOUT.columns, rows: ATLAS_LAYOUT.rows,
    },
  }]];
});

/* Artist-authored primary sheet (and its coloured variant, generated from it
   by scripts/generate-color-main-icons.mjs). Keep their stable ids separate
   from generated review/reference atlases so saved preferences survive asset
   regeneration. */
const svgSet = (id, label, filename) => {
  const data = byFilename[filename];
  return data ? [[id, {
    id, label, base: 'marks',
    icons: Object.fromEntries(slots.map((slot, index) => [`${slot.domain}:${slot.key}`, `atlas:${id}:${index}`])),
    atlas: {
      data, mime: 'image/svg+xml', group: 'all', count: slots.length,
      columns: ATLAS_LAYOUT.columns, rows: ATLAS_LAYOUT.rows,
    },
  }]] : [];
};
const mainSet = svgSet('main', 'Main Icons', 'main-icons.svg');
const mainColorSet = svgSet('main-color', 'Main Icons (Colour)', 'main-icons-color.svg');
const mainEmojiSet = svgSet('main-emoji', 'Main Icons (Emoji)', 'main-icons-emoji.svg');
const mainLineSet = svgSet('main-line', 'Main Icons (Line Art)', 'main-icons-line.svg');
/* An original icon family (not derived from the artist's sheet) — see
   scripts/generate-sigil-icons.mjs. */
const sigilSet = svgSet('sigils', 'Sigils', 'sigil-icons.svg');

export const ATLAS_SETS = Object.fromEntries([...mainSet, ...mainColorSet, ...mainEmojiSet, ...mainLineSet, ...sigilSet, ...generatedSets]);

registerIconSets(ATLAS_SETS);
