/* The complete-set sheets in assets/icon-atlas/sets, registered as selectable
   icon sets. Vite emits each sheet as its own asset URL, so a sheet is only
   fetched once a tile actually paints from it — importing this module costs
   nothing until a player picks one of these sets.

   Sheets are generated by scripts/generate-icon-set-atlases.mjs and named after
   the built-in set they depict; a set with no sheet on disk simply contributes
   nothing here. */
import { ATLAS_LAYOUT, atlasSlots, registerIconSets } from './iconSets.js';
import mainIcons from '../assets/icon-atlas/sets/main-icons.svg?url';

const byFilename = { 'main-icons.svg': mainIcons };

const slots = atlasSlots('all');

/* Artist-authored primary sheet (and its coloured variant, generated from it
   by scripts/generate-color-main-icons.mjs). Keep their stable ids separate
   from generated review/reference atlases so saved preferences survive asset
   regeneration. */
const svgSet = (id, label, filename) => {
  const data = byFilename[filename];
  return data ? [[id, {
    id, label, base: 'marks',
    icons: Object.fromEntries(slots.map((slot, index) => [`${slot.domain}:${slot.key}`, `atlas:${id}:${index}`])),
    atlas: {
      data, mime: 'image/svg+xml', group: 'all', count: slots.length,
      columns: ATLAS_LAYOUT.columns, rows: ATLAS_LAYOUT.rows,
    },
  }]] : [];
};
const mainSet = svgSet('main', 'Main Icons', 'main-icons.svg');

export const ATLAS_SETS = Object.fromEntries(mainSet);

registerIconSets(ATLAS_SETS);
