// Concrete worked examples for every documented mechanic, using real card
// names, real enemies, and the exact numbers from src/engine/data.js. Each
// example plays out as three beats — setup, action, result — matching the
// three scenes of the battle demonstration. `card` labels the demo card with
// the real source of the effect where one exists.
export const MECHANIC_EXAMPLES = {
  health: {
    card: 'Brace',
    setup: 'You are at 24/32 Health with 0 Block and 2 Plating while a Gear Husk telegraphs Attack 14.',
    action: 'You End Turn without defending, so the full 14 lands against only 2 Plating.',
    result: 'Plating soaks 2, the other 12 comes off Health — you drop to 12/32. Reach 0 and the descent ends.',
  },
  gold: {
    card: 'Blast Suit',
    setup: 'You finish a fight carrying 42 Gold and step into a merchant Shop selling Blast Suit for 30.',
    action: 'You spend 30 Gold to buy Blast Suit.',
    result: 'Your Gold drops to 12 and the card joins your deck for the rest of the run.',
  },
  deck: {
    card: 'Controlled Blast',
    setup: 'Your run deck holds 12 cards; this combat they shuffle into a draw pile and you open a 5-card hand.',
    action: 'You tap the deck counter to inspect every card still to come.',
    result: 'Cards you take at rewards, like Controlled Blast, grow this deck permanently — Exhaust only removes them for the current fight.',
  },
  mines: {
    card: 'Munitions Cache',
    setup: 'A Topsoil board is dealt with 10 hidden mines, so the HUD reads Mines 10.',
    action: 'You place 3 flags on tiles you believe are mined.',
    result: 'The counter now shows Mines 7 — total mines minus your flags — an estimate that is wrong wherever a flag is.',
  },
  turn: {
    card: 'Probe',
    setup: 'It is Turn 1 and the Minelayer Imp shows intent Attack 8.',
    action: 'You spend your Energy and press End Turn.',
    result: 'The Imp resolves its 8-damage attack, the Turn ticks to 2, and your Energy and Picks refill.',
  },
  reveal: {
    card: 'Probe',
    setup: 'A revealed 0 sits next to a cluster of hidden tiles on the Topsoil board.',
    action: 'You spend 1 Pick to reveal a tile touching that 0.',
    result: 'It is safe, and its own 0 cascades open a whole pocket of connected safe ground for free.',
  },
  detonate: {
    card: 'Controlled Blast',
    setup: 'You hold Controlled Blast and a tile you already scanned as mined sits on the board.',
    action: 'You play Controlled Blast on that mined tile.',
    result: 'It detonates under control for 12 to all enemies and costs you 3 HP — a controlled blast, so no uncontrolled mine damage.',
  },
  scan: {
    card: 'Scan',
    setup: 'You draw Scan (0 Energy) with a suspicious tile sitting beside a revealed 3.',
    action: 'You play Scan on that tile.',
    result: 'It is marked mined without opening and you draw 1 card — now Marked Charge or Kill Zone can exploit the known mine.',
  },
  defuse: {
    card: 'Fuse Cutter',
    setup: 'A confirmed mine blocks the safe path and you are holding Fuse Cutter.',
    action: 'You play Fuse Cutter on the mined tile.',
    result: 'The mine is removed and the tile revealed safely, and because it was mined you deal 8 to a random enemy.',
  },
  chord: {
    card: 'Chord',
    setup: 'A revealed 1 has three hidden neighbors; you have flagged exactly the one you read as the mine.',
    action: 'You play a 0-Energy Chord card and choose the revealed 1.',
    result: 'Its two unflagged neighbors open at once — but if your flag were on a safe tile, the real mine would detonate and the Chord would fail.',
  },
  entomb: {
    card: 'Entomb',
    setup: 'One stubborn mine is wedged in a corner you do not want to risk, and you hold Entomb.',
    action: 'You play Entomb on that hidden tile.',
    result: 'It is sealed forever — it can never detonate and already counts as resolved toward Full Clear.',
  },
  flag: {
    card: 'Munitions Cache',
    setup: 'A revealed 1 touches a single hidden tile.',
    action: 'You long-press that tile to place a Flag.',
    result: 'It is a free note, not proof: the Mines counter drops by 1, but a wrong flag still hides a live mine.',
  },
  'verified flag': {
    card: 'Munitions Cache',
    setup: 'You hold Munitions Cache with several hidden mines still on the board.',
    action: 'You play it to verified-flag 2 random mines.',
    result: 'Those two flags are guaranteed correct — unlike manual flags, they can safely anchor a Chord.',
  },
  'full clear': {
    card: 'Landslide',
    setup: 'Two enemies still live, but every remaining tile is safe or already resolved.',
    action: 'You reveal the last safe tile, completing the board.',
    result: 'The board deals 50 to all enemies and hands you an upgraded card; if any survive, it re-seals into a fresh board.',
  },
  instinct: {
    card: 'Probe',
    setup: 'At 30/32 Health you misjudge a tile and reveal what turns out to be a mine.',
    action: 'The reveal would normally explode for mine damage.',
    result: 'Instinct catches the first such mistake — the tile is verified-flagged instead of detonating, so you take no damage this once.',
  },
  'mine damage': {
    card: 'Blast Suit',
    setup: 'In the Topsoil Crypts you hold 0 Block and 6 Plating when you accidentally reveal a mine.',
    action: 'The uncontrolled mine detonates for 8 mine damage.',
    result: 'It ignores Block entirely, but Plating soaks it: 6 absorbed, only 2 reaches Health.',
  },
  lair: {
    card: 'Probe',
    setup: 'A Stone Warden owns a tinted lair region; one lair tile is a hidden safe 3.',
    action: 'You reveal that lair-3 tile.',
    result: 'It deals 3 straight to the Warden. A lair mine instead deals 10, and Entombing a lair tile deals 3.',
  },
  construct: {
    card: 'Sentry',
    setup: 'You have a revealed tile and are holding Sentry.',
    action: 'You play Sentry on that open tile.',
    result: 'It becomes a construct dealing 5 to a random enemy at the end of every turn, and it soaks the next enemy board attack before it reaches you.',
  },
  block: {
    card: 'Brace',
    setup: 'The Marsh Shade telegraphs Attack 9 and you hold Brace.',
    action: 'You play Brace for 5 Block, then End Turn.',
    result: 'Block absorbs 5 of the 9, so only 4 reaches Health — then Block resets to 0 at the start of your next turn.',
  },
  plating: {
    card: 'Blast Suit',
    setup: 'You play Blast Suit for 4 Plating before a turn where you plan to crack mines open.',
    action: 'An uncontrolled mine later goes off while you hold 0 Block.',
    result: 'Plating persists across turns and soaks the mine damage that Block cannot touch, saving your Health.',
  },
  insight: {
    card: 'Deduction',
    setup: 'Playing the Surveyor you scan several tiles and bank 3 Insight.',
    action: 'You play Deduction, spending all 3 Insight.',
    result: 'Deduction deals 3 damage per point spent — 9 to the target — then your Insight returns to 0.',
  },
  picks: {
    card: 'Probe',
    setup: 'You start the turn with 3 Picks, your refilled maximum.',
    action: 'You manually reveal 2 tiles, then play Probe, which reveals a third without spending a Pick.',
    result: 'You have 1 Pick left — cards only consume Picks when they say Spend, and bonus Picks can push you above your max.',
  },
  'max picks': {
    card: 'Probe',
    setup: 'Training at a Camp raises your Max Picks from 3 to 4.',
    action: 'Each new turn now refills you to 4 Picks instead of 3.',
    result: 'A single Vertigo curse would claw that back by 1 per copy, though never below 1.',
  },
  energy: {
    card: 'Fault Line',
    setup: 'You begin the turn with 3 Energy.',
    action: 'You play Fault Line (1) and Controlled Blast (1).',
    result: '1 Energy remains, and unspent Energy does not carry over — it refills to 3 next turn.',
  },
  power: {
    card: 'Powder Keg',
    setup: 'You hold Powder Keg, a Power card, with 1 Energy to spend.',
    action: 'You play Powder Keg.',
    result: 'Instead of hitting the discard, it stays active all combat: every mine that detonates now deals 5 to all enemies.',
  },
  exhaust: {
    card: 'Gravebind',
    setup: 'You play Gravebind, whose text ends in Exhaust.',
    action: 'It resolves, applying Exposed and Jammed to the boss.',
    result: 'Rather than cycling back into your draws, Gravebind is Exhausted — gone for the rest of this combat but back next fight.',
  },
  exposed: {
    card: 'Fault Line',
    setup: 'The Minelayer Imp sits at 20 HP; you hold Fault Line and Probe.',
    action: 'Fault Line deals 5 and applies 1 Exposed, then you play Probe on a safe tile for 4.',
    result: 'Exposed adds 25% to that Probe hit — 4 becomes 5 — and one Exposed stack is spent.',
  },
  jammed: {
    card: 'Signal Jam',
    setup: 'The Gear Husk telegraphs a heavy Attack 14 and you hold Signal Jam.',
    action: 'You play Signal Jam, applying 1 Jammed.',
    result: 'Its next direct attack is cut 40% — the 14 lands as 8 — and the Jammed stack is used up.',
  },
  sundered: {
    card: 'Sundering Chalk',
    setup: 'A Stone Warden has stacked 12 Block and is about to fortify again; you hold Sundering Chalk.',
    action: 'You play Sundering Chalk to apply 1 Sundered.',
    result: 'Its 12 Block is stripped immediately, and the Block it gains on its next action is halved.',
  },
  armoured: {
    card: 'Sundering Chalk',
    setup: 'In Stratum 2 you meet an Armoured Tunneler Grub that opens with 12 Block (8 plus 4 per depth).',
    action: 'You attack into it before it acts.',
    result: 'That opening Block soaks your hits but expires right after the Grub’s first action — or strip it early with Sundered.',
  },
  burrowing: {
    card: 'Probe',
    setup: 'A Burrowing Minelayer Imp starts underground: untargetable and unable to act.',
    action: 'You reveal 3 safe tiles in a single turn.',
    result: 'That forces it above ground, where it can finally be targeted and resumes its attack pattern.',
  },
  unstable: {
    card: 'Blast Suit',
    setup: 'An Unstable Fog Wisp (1 HP) is about to die to your Sentry.',
    action: 'You let the construct finish it.',
    result: 'It explodes on death for a blast that bypasses Block — but your Plating can absorb it, so hold Plating before the kill.',
  },
  cursed: {
    card: 'Dud',
    setup: 'A Cursed enemy slips an unplayable Dud into your combat discard.',
    action: 'The Dud later turns up in your hand, taking a slot.',
    result: 'You cannot play it, but it Exhausts itself at end of turn — gone for the rest of the fight.',
  },
  claustrophobia: {
    card: 'Claustrophobia',
    setup: 'You are carrying 2 Claustrophobia curses in your deck.',
    action: 'You enter a new combat.',
    result: 'Every board this run spawns with 4 extra mines (2 per copy) — denser fields, more to flag or defuse.',
  },
  vertigo: {
    card: 'Vertigo',
    setup: 'One Vertigo curse sits in your deck; your Max Picks is normally 3.',
    action: 'Combat begins.',
    result: 'Vertigo lowers Max Picks by 1 per copy to 2, so each turn refills fewer manual digs — never below 1.',
  },
  exhaustion: {
    card: 'Exhaustion',
    setup: 'You picked up an Exhaustion curse; you normally draw 5 cards a turn.',
    action: 'A new turn starts.',
    result: 'You draw 1 fewer per copy — 4 cards — floored at 3.',
  },
  'night terrors': {
    card: 'Night Terrors',
    setup: 'A Night Terrors curse rides in your deck; you would normally open with 3 Energy.',
    action: 'Turn 1 of a fight begins.',
    result: 'Night Terrors removes 1 Energy from that first turn per copy, so you open with 2.',
  },
  paranoia: {
    card: 'Paranoia',
    setup: 'One Paranoia curse is in your deck.',
    action: 'Combat starts and the board is dealt.',
    result: 'Paranoia auto-places 1 ordinary flag on a safe hidden tile — a decoy you must spot and clear before trusting a Chord.',
  },
  sapper: {
    card: 'Short Fuse',
    setup: 'Playing the Sapper, you line up a scanned mine and hold Short Fuse.',
    action: 'You detonate it — your first controlled detonation this turn.',
    result: 'Breachcraft adds 4 damage to every enemy on top of Short Fuse’s own hit.',
  },
  surveyor: {
    card: 'Scan',
    setup: 'As the Surveyor you play Scan repeatedly, scanning tiles one at a time.',
    action: 'You scan your 4th new tile of the fight.',
    result: 'Field Method rewards every 4th newly scanned tile with 1 Energy and 1 Insight.',
  },
  terraformer: {
    card: 'Sentry',
    setup: 'Playing the Terraformer, you hold Sentry over a revealed tile.',
    action: 'You build the Sentry construct.',
    result: 'Master Builder grants 2 Plating each time a Construct is built — stacking defense as you fortify.',
  },
  lamplighter: {
    card: 'Probe',
    setup: 'As the Lamplighter you find a revealed 0 beside a large unopened pocket.',
    action: 'You reveal it and a cascade flips 6 connected tiles.',
    result: 'Because it was your first cascade of at least 4 tiles this turn, Kindle refunds 1 Energy.',
  },
  gambler: {
    card: 'Munitions Cache',
    setup: 'Playing the Gambler, a revealed 1 pins down exactly one hidden mine.',
    action: 'You place your first correct manual Flag of the turn on it.',
    result: 'Lucky Read immediately draws you 1 card.',
  },
  chirurgeon: {
    card: 'Brace',
    setup: 'As the Chirurgeon you take an 8-damage hit — the first Health you have lost this turn.',
    action: 'The damage resolves.',
    result: 'Triage converts that first pain into 5 Block, softening the next blow.',
  },
  archivist: {
    card: 'Eureka',
    setup: 'Playing the Archivist, you play Eureka, which Exhausts.',
    action: 'It Exhausts — the first card Exhausted this turn.',
    result: 'Cross-Reference draws you 1 card to replace it.',
  },
  warden: {
    card: 'Brace',
    setup: 'As the Warden you end the turn holding 8 Block.',
    action: 'The new turn begins, when Block would normally reset to 0.',
    result: 'Hold Fast keeps a quarter of it — you start with 2 Block instead of none.',
  },
  hexwright: {
    card: 'Probe',
    setup: 'Playing the Hexwright, you reveal a tile that turns out to be a 4.',
    action: 'The number 4 (which is 3 or higher) is exposed.',
    result: 'Hot Number deals 2 damage to every enemy — turning careful digging into chip damage.',
  },
  revenant: {
    card: 'Brace',
    setup: 'As the Revenant you are at 6 HP when a Gear Husk’s Attack 14 lands — lethal.',
    action: 'The hit resolves for the first time this combat.',
    result: 'Not Yet leaves you alive at 1 HP instead of dead, buying one more turn to stabilize.',
  },
};
