/* Additional event content. The engine resolves the compact outcome metadata so
   this bank can grow without adding another branch to eventChoice for each room. */

const QUIZZES = [
  ['mean-median', '⚖️', 'The Crooked Average', 'One delver has 100 gold; nine have none. Which best describes the typical purse?', 'Median: 0 gold', 'Mean: 10 gold', 'Mode: 100 gold', 'The median resists the single extreme purse; the mean is pulled upward.'],
  ['gambler-fallacy', '🪙', 'Five Tails in the Dust', 'A fair coin has landed tails five times. What is the chance of heads next?', '50%', 'More than 50%', 'Less than 50%', 'Independent flips do not remember the previous streak.'],
  ['expected-die', '🎲', 'The Bone Die', 'What is the expected value of one fair six-sided die?', '3.5', '3', '4', 'Average all six equally likely faces: 21 divided by 6 is 3.5.'],
  ['conditional-coin', '🪙', 'At Least One Head', 'Two fair coins are tossed. Given at least one head, what is the chance both are heads?', '1/3', '1/2', '1/4', 'The remaining equally likely outcomes are HH, HT, and TH.'],
  ['large-numbers', '📈', 'The Long Ledger', 'What happens to a sample average as independent trials accumulate?', 'It tends toward the expected value', 'It becomes exactly correct after 100 trials', 'It grows without limit', 'The law of large numbers describes convergence, not a magic sample size.'],
  ['simpson', '🌀', "Simpson's Staircase", 'Two groups each favor treatment A, yet the combined data favor B. What can cause this?', 'Different group sizes or confounding', 'Arithmetic becomes invalid', 'The samples must be identical', 'Aggregation can reverse a trend when a lurking variable changes group weights.'],
  ['regression-mean', '🎯', 'The Champion Returns', 'An exceptionally lucky score is followed by a more ordinary score. The simplest explanation?', 'Regression toward the mean', 'A permanent curse', 'The rules changed', 'Extreme observations often combine skill with temporary noise.'],
  ['survivorship', '🛡️', 'Armor of the Survivors', 'You reinforce only the places where returning armor is damaged. What did you overlook?', 'Armor that was hit where no one returned', 'The most common scratch', 'The average armor weight', 'Survivorship bias hides failures missing from the observed sample.'],
  ['correlation', '🔗', 'Two Rising Shadows', 'Torch sales and cave accidents rise together. What can you conclude?', 'Association, not necessarily causation', 'Torches cause every accident', 'Accidents manufacture torches', 'A third factor, such as more cave traffic, may drive both.'],
  ['p-value', '🧪', 'The Small P-Rune', 'A p-value of 0.03 means what?', 'The data are unusual if the null model is true', 'The null has a 3% chance of being true', 'The result has a 97% chance of repeating', 'A p-value conditions on the null; it is not the probability that the null is true.'],
  ['confidence', '📏', 'Ninety-Five Runes', 'What does a 95% confidence procedure promise?', 'About 95% of intervals from repeated samples cover the true value', 'This interval has a mystical 95% truth chance', '95% of the data lie inside every interval', 'Coverage describes the long-run procedure used to construct intervals.'],
  ['sampling-bias', '📨', 'The Voluntary Census', 'A danger survey only hears from delvers angry enough to reply. The main problem?', 'Self-selection bias', 'Too many random samples', 'Perfect blinding', 'Volunteers can differ systematically from silent delvers.'],
  ['independence', '✂️', 'Separate Tunnels', 'Events A and B are independent when…', 'Knowing A does not change the probability of B', 'They can never occur together', 'They have equal probabilities', 'Independence concerns information, not equality or mutual exclusion.'],
  ['permutations', '🔢', 'Three Runes in Order', 'How many orders can three distinct runes take?', '6', '3', '9', 'There are 3 × 2 × 1 permutations.'],
  ['combinations', '🗝️', 'Choose Two Keys', 'How many unordered pairs can be chosen from four distinct keys?', '6', '8', '12', 'Four choose two equals 4×3 divided by 2.'],
  ['binomial', '🏹', 'Exactly Two Hits', 'With three independent 50% shots, what is the chance of exactly two hits?', '3/8', '1/8', '1/2', 'There are three two-hit sequences among eight equally likely sequences.'],
  ['geometric', '⏳', 'Until the First Six', 'With a fair die, how many rolls are expected until the first six?', '6', '3.5', '36', 'A geometric wait with success probability 1/6 has mean 6.'],
  ['poisson', '🦇', 'Bats per Minute', 'Independent rare arrivals at a stable average rate are often modeled by…', 'A Poisson distribution', 'A uniform distribution', 'A deterministic line', 'The Poisson model counts independent arrivals over an interval.'],
  ['normal-rule', '🔔', 'The Bell Chamber', 'Roughly what fraction of normal observations lie within one standard deviation?', '68%', '50%', '95%', 'The 68–95–99.7 rule gives the familiar normal ranges.'],
  ['central-limit', '🏛️', 'Averages of Many Rooms', 'Why do many sample averages look approximately normal?', 'The central limit theorem', 'Every raw population is normal', 'Averages erase all uncertainty', 'Under broad conditions, standardized sums approach a normal shape.'],
  ['variance', '📐', 'The Spread Rune', 'Variance measures…', 'Average squared distance from the mean', 'The largest observation', 'The middle observation', 'Squaring makes deviations positive and emphasizes larger distances.'],
  ['standard-deviation', '📏', 'Root of the Spread', 'Standard deviation is useful because it is…', 'In the original measurement units', 'Always between zero and one', 'The same as the mean', 'It is the square root of variance and returns to the original units.'],
  ['ticket-ev', '🎟️', 'The One-in-Ten Ticket', 'A ticket costs 6 gold and has a 10% chance to pay 50. Its net expected value?', '−1 gold', '+5 gold', '+44 gold', 'Expected payout is 5 gold; subtract the 6-gold cost.'],
  ['risk-aversion', '🛡️', 'Certain Thirty', 'Why might someone prefer certain 30 gold over a 50/50 chance at 100 or nothing?', 'Diminishing marginal utility', 'The gamble has lower expected gold', 'Probabilities cannot be compared', 'The gamble has higher expected gold, but wealth can have concave utility.'],
  ['nash', '♟️', 'No One Moves Alone', 'A Nash equilibrium is a profile where…', 'No player benefits by changing alone', 'Everyone receives the same payoff', 'The outcome is always socially best', 'Equilibrium is about unilateral deviations, not fairness or efficiency.'],
  ['dominant-strategy', '👑', 'The Dominant Move', 'A dominant strategy is best…', 'Against every strategy opponents might choose', 'Only when opponents cooperate', 'Only after seeing the outcome', 'Dominance compares a move across all opposing choices.'],
  ['zero-sum', '⚔️', 'One Purse Between Two', 'In a zero-sum game…', "One player's gain equals another's loss", 'Both players must lose', 'Cooperation is impossible in every form', 'The total payoff is fixed; distribution changes but the sum does not.'],
  ['pareto', '◆', 'A Better Chamber', 'A Pareto improvement makes…', 'Someone better off and no one worse off', 'Everyone equally wealthy', 'The richest player poorer', 'Pareto improvement is deliberately silent about equality.'],
  ['stag-hunt', '🦌', 'Stag or Rat', 'The Stag Hunt mainly illustrates tension between…', 'Payoff-dominant cooperation and safer individual action', 'Pure chance and certainty', 'Past and future costs', 'The group prize is largest together, while the smaller solo prize is safer.'],
  ['chicken-game', '🛤️', 'Two Carts, One Track', 'In Chicken, the worst outcome occurs when…', 'Neither side yields', 'Both sides yield', 'Exactly one side yields', 'Mutual stubbornness creates the disastrous collision.'],
  ['ultimatum', '🤝', 'Split the Cache', 'Why are tiny offers often rejected in ultimatum games?', 'Fairness and punishment matter alongside money', 'Responders cannot count', 'Rejection creates more gold', 'People may pay a cost to punish an allocation they consider unfair.'],
  ['public-goods', '🏮', 'The Shared Lantern', 'A public good is typically…', 'Non-excludable and non-rival', 'Private and quickly consumed', 'Available only to its buyer', 'People can benefit without being excluded and without exhausting others’ benefit.'],
  ['backward-induction', '↩️', 'The Last Door First', 'Backward induction solves a finite sequential game by…', 'Reasoning backward from final decisions', 'Ignoring future choices', 'Selecting the first available move', 'Later rational responses determine what earlier moves are sensible.'],
  ['mixed-strategy', '🎭', 'Unpredictable Footwork', 'Why randomize in matching pennies?', 'To prevent an opponent exploiting a pattern', 'To make one face intrinsically stronger', 'To guarantee every round', 'The equilibrium mixture removes predictable weakness, not ordinary variance.'],
  ['condorcet', '🗳️', 'The Pairwise Champion', 'A Condorcet winner is an option that…', 'Beats every other option head-to-head', 'Has exactly half the votes', 'Is ranked last by no one', 'It is defined through pairwise majority contests.'],
  ['arrow', '🏹', "Arrow's Warning", 'What does Arrow’s theorem reveal about rank voting with three or more options?', 'No system satisfies every reasonable fairness condition', 'Every election must tie', 'Majority voting is always dictatorial', 'The listed fairness requirements cannot all coexist in a single rank-order system.'],
  ['anchoring', '⚓', 'The First Price Spoken', 'An irrelevant opening price pulls later estimates toward it. This is…', 'Anchoring', 'Regression', 'Randomization', 'Initial numbers can influence judgment even when they contain little information.'],
  ['availability', '🔥', 'The Vivid Collapse', 'After hearing one dramatic cave-in, you greatly overestimate all cave-in risk. This is…', 'The availability heuristic', 'The law of large numbers', 'Dominance', 'Memorable examples come to mind more easily than representative base rates.'],
  ['loss-aversion', '💔', 'The Pain of Ten Gold', 'Losing 10 gold often feels stronger than gaining 10 gold. This is…', 'Loss aversion', 'Risk neutrality', 'Independence', 'Reference-dependent preferences often weight losses more heavily than equal gains.'],
  ['confirmation', '🔍', 'Only Friendly Runes', 'Seeking only evidence that supports your map is…', 'Confirmation bias', 'Stratified sampling', 'Backward induction', 'Good testing actively searches for observations that could prove a belief wrong.'],
  ['base-rate', '📚', 'The Rare Mimic', 'A detector is impressive, but mimics are extremely rare. What must not be ignored?', 'The base rate', 'The largest payoff', 'The sample maximum', 'Posterior probability depends on prevalence as well as test accuracy.'],
  ['prosecutor', '⚖️', "The Prosecutor's Rune", 'A rare matching trace is presented as the chance the accused is innocent. The error?', 'Confusing P(evidence|innocent) with P(innocent|evidence)', 'Using too many witnesses', 'Calculating an average', 'Reversing conditional probabilities ignores priors and alternative sources.'],
  ['false-positive', '🚨', 'The Alarm That Cries Rat', 'Many alarms among thousands of safe rooms can outnumber true alarms when danger is rare. This emphasizes…', 'False positives and prevalence', 'Only sensitivity', 'Guaranteed guilt after an alarm', 'Even a modest false-positive rate can dominate a very rare true condition.'],
  ['expected-maximum', '🎲', 'Keep the Higher Die', 'Roll two fair dice and keep the higher. Is its expected value above or below 3.5?', 'Above 3.5', 'Exactly 3.5', 'Below 3.5', 'Taking a maximum preserves high rolls while replacing many low ones.'],
];

const DILEMMAS = [
  ['signal-fire', '🔥', 'The Shared Signal Fire', 'Three parties need the beacon, but each hopes another pays for fuel.', 'Contribute fuel', 'Support the public good and make the signal reliable.', 'Wait for the others', 'Free-ride and gamble that enough fuel appears.', 'Public goods invite free-riding because contributors cannot easily exclude noncontributors.'],
  ['shared-rope', '🪢', 'The Common Rope', 'Every team may cut a little rope for itself; too many cuts ruin the crossing.', 'Take only the marked length', 'Preserve the shared resource.', 'Cut an extra coil', 'Gain more now and risk the crossing.', 'Individual extraction can collectively destroy a renewable commons.'],
  ['sealed-urn', '🏺', 'The Ambiguous Urn', 'One urn has known odds; the other hides its color mix.', 'Choose the known odds', 'Avoid uncompensated ambiguity.', 'Choose the hidden urn', 'Accept ambiguity for a larger possible cache.', 'People often distinguish measurable risk from uncertainty with unknown probabilities.'],
  ['bridge-commitment', '🌉', 'The One-Way Bridge', 'Two carts approach. A visible brake lock can make yielding impossible.', 'Signal and coordinate first', 'Avoid a destructive commitment race.', 'Lock the brake', 'Make a credible threat and hope the other yields.', 'Commitment can shift bargaining power while increasing the chance of catastrophe.'],
  ['map-auction', '🗺️', 'The Map Auction', 'Every bidder estimates the same unknown map value with noisy information.', 'Shade for estimation error', 'Account for winning being bad news about your estimate.', 'Bid your estimate aggressively', 'Treat your estimate as exact.', 'In common-value auctions, the winner is often the bidder with the most optimistic error.'],
  ['expedition-vote', '🗳️', 'The Expedition Vote', 'Three routes can produce a preference cycle: A beats B, B beats C, C beats A.', 'Agree on a voting rule first', 'Make the agenda transparent before voting.', 'Let the chair choose the order', 'Exploit agenda control for your route.', 'Pairwise majority preferences can cycle, giving agenda setters real power.'],
  ['wounded-rival', '🩹', 'The Wounded Rival', 'Helping a rival costs supplies now but may begin a repeated alliance.', 'Treat the wound', 'Invest in reciprocity and reputation.', 'Take the rival’s pack', 'Maximize the one-shot payoff.', 'Repeated interaction can reward cooperation that a single encounter would not.'],
  ['ration-pool', '🥖', 'The Ration Pool', 'Private hunger is visible only to each delver; the group must allocate a common store.', 'Report needs honestly', 'Use a rule the group can sustain.', 'Exaggerate your need', 'Claim more before others do.', 'Mechanisms fail when participants benefit from misreporting private information.'],
  ['cursed-coin', '🪙', 'The Cursed Coin', 'The coin offers small gains often and a devastating rare loss.', 'Price the tail risk', 'Judge the entire distribution.', 'Count the frequent wins', 'Let the high win rate guide you.', 'A strategy can win most rounds while carrying negative expected value or ruinous tail risk.'],
  ['oracle-information', '🔮', 'The Costly Oracle', 'An oracle sells a clue before you choose between two tunnels.', 'Value the clue by changed decisions', 'Pay only for information that can alter action.', 'Buy every clue', 'More information must always be valuable.', 'Information has instrumental value only when it can improve a choice enough to cover its cost.'],
  ['mine-insurance', '📜', 'Mine Insurance', 'Full insurance makes careless digging cheaper for the insured.', 'Keep a deductible', 'Preserve an incentive to avoid damage.', 'Cover every loss', 'Remove all personal consequence.', 'Insurance can create moral hazard when protection changes behavior.'],
  ['single-file', '🚶', 'The Narrow Stair', 'Everyone wants to go first, but pushing makes the entire queue slower.', 'Use an agreed order', 'Coordinate for higher total throughput.', 'Push to the front', 'Gain position if others remain orderly.', 'Congestion games can make individually tempting actions collectively inefficient.'],
  ['volunteer', '🛎️', "The Volunteer's Bell", 'Someone must ring the dangerous bell or everyone loses the route.', 'Volunteer deliberately', 'Pay the cost and secure the group benefit.', 'Wait in silence', 'Hope another delver accepts the cost.', 'Volunteer dilemmas combine a shared benefit with an incentive for each person to wait.'],
  ['centipede', '🐛', 'The Centipede Cache', 'Passing the cache grows it, but the next player may take everything.', 'Pass once under a trust pact', 'Use repetition or reputation to support growth.', 'Take immediately', 'Apply strict one-shot backward induction.', 'Finite backward induction predicts early taking, while human trust often sustains growth.'],
  ['trust-game', '🤲', 'The Multiplied Purse', 'Gold sent to a stranger triples; the stranger decides how much to return.', 'Send a measured stake', 'Test reciprocity without risking everything.', 'Send the whole purse', 'Seek the largest cooperative surplus.', 'Trust can create surplus, but exposure should reflect evidence about reciprocity.'],
  ['dictator-game', '👤', "The Dictator's Split", 'You alone decide how to divide a cache with a powerless stranger.', 'Offer a fair share', 'Value fairness and future reputation.', 'Keep everything', 'Take the maximum immediate payoff.', 'Dictator games reveal social preferences even without strategic retaliation.'],
  ['coordination-bells', '🔔', 'The Two Bells', 'Both teams benefit only if they ring the same bell without speaking.', 'Choose the marked bell', 'Use the obvious focal point.', 'Choose the hidden bell', 'Outthink the other team.', 'Salient focal points help people coordinate when communication is impossible.'],
  ['minority-game', '🕯️', 'The Cooler Tunnel', 'Everyone wants the less crowded tunnel, but the choice itself changes which is less crowded.', 'Randomize your route', 'Avoid a predictable crowding pattern.', 'Follow yesterday’s minority', 'Assume the last winner repeats.', 'Adaptive crowds can create oscillation; predictable rules defeat themselves.'],
  ['lemons', '🍋', 'The Used Lantern Market', 'Sellers know lantern quality; buyers cannot distinguish sound lamps from bad ones.', 'Offer inspection or warranty', 'Create a credible quality signal.', 'Sell without evidence', 'Ask buyers to trust the average.', 'Information asymmetry can drive good products from a market.'],
  ['moral-hazard', '🧨', 'Borrowed Blasting Powder', 'A lender absorbs losses while the borrower keeps most upside.', 'Share downside as well as upside', 'Align incentives before lending.', 'Fund the largest blast', 'Chase the maximum possible return.', 'Limited downside can encourage excessive risk-taking.'],
  ['adverse-selection', '🩺', 'The Healing Pool', 'Only the sickest delvers eagerly buy a plan priced for average health.', 'Price or pool with better information', 'Address who chooses to enter.', 'Raise one price for everyone', 'Assume buyers are representative.', 'Hidden types can make the participating group riskier than the full population.'],
  ['free-rider', '🧹', 'Clearing the Public Passage', 'All teams benefit from cleared rubble whether or not they help.', 'Join the work crew', 'Contribute to the shared benefit.', 'Slip past afterward', 'Keep your strength while others work.', 'Non-excludable benefits make free-riding individually tempting.'],
  ['credible-threat', '🐉', 'The Sleeping Dragon Threat', 'A guard threatens to wake the dragon after any trespass—even though doing so would destroy his post.', 'Question the threat', 'Ask whether carrying it out would be rational.', 'Pay the guard immediately', 'Treat every stated threat as binding.', 'A threat influences behavior only if it is credible when the decision point arrives.'],
  ['commitment-device', '🔒', 'The Locked Ration Box', 'Tomorrow’s hungry self will break today’s ration plan.', 'Set a timed lock', 'Commit in advance against predictable temptation.', 'Rely on tomorrow’s resolve', 'Keep every option open.', 'Commitment devices trade flexibility for protection from time-inconsistent preferences.'],
  ['common-knowledge', '👁️', 'The Blue-Eyed Delvers', 'Everyone sees the mark, but action begins only after its existence is publicly announced.', 'Make the fact public', 'Turn shared observation into common knowledge.', 'Whisper it privately', 'Tell each delver separately.', 'Coordination may require everyone to know that everyone knows, recursively.'],
  ['focal-point', '✳️', 'Meet Without a Map', 'Separated teams must independently choose one of many crypt gates to reunite.', 'Choose the uniquely decorated gate', 'Use salience as a coordination point.', 'Choose a random plain gate', 'Avoid being too obvious.', 'Schelling points coordinate expectations without explicit communication.'],
  ['information-cascade', '🐑', 'Footprints to the Left', 'Two earlier delvers went left; your private clue weakly favors right.', 'Weigh your clue and their information', 'Do not count copied choices as independent evidence.', 'Follow the footprints automatically', 'Assume every predecessor had a separate strong clue.', 'Information cascades form when people rationally imitate, hiding their private evidence.'],
  ['winner-curse', '👑', "The Winner's Relic", 'You win a relic that everyone estimated independently. What should the victory itself suggest?', 'Your estimate may have been unusually high', 'The relic must be worth your bid', 'All other estimates were irrelevant', 'Winning a common-value auction is evidence that you were the most optimistic.'],
  ['endowment', '🎒', 'The Trinket Already Yours', 'You demand more to sell a trinket than you would have paid to acquire it.', 'Revalue it without ownership', 'Use the same comparison in either direction.', 'Keep it because possession proves value', 'Treat ownership as new evidence.', 'The endowment effect makes ownership itself inflate perceived value.'],
  ['framing', '🖼️', 'Lives Saved or Lost', 'The same outcome sounds attractive as lives saved and frightening as lives lost.', 'Translate both frames to outcomes', 'Compare equivalent probabilities directly.', 'Choose the positive wording', 'Let presentation determine value.', 'Equivalent descriptions can produce different choices through framing effects.'],
  ['decoy', '🪤', 'The Inferior Pickaxe', 'A clearly worse third pickaxe makes one of two original choices look better.', 'Ignore dominated options', 'Compare the original tradeoff directly.', 'Follow the newly attractive choice', 'Let the decoy set the comparison.', 'An asymmetrically dominated decoy can shift preferences without adding real value.'],
  ['hyperbolic', '⌛', 'Gold Now or Later', 'You prefer 11 gold tomorrow over 10 today, but later prefer 10 immediately over 11 tomorrow.', 'Precommit to the patient choice', 'Protect the earlier plan from present bias.', 'Always take immediate gold', 'Let each future self decide again.', 'Hyperbolic discounting creates preference reversals as rewards become immediate.'],
  ['status-quo', '🪨', 'The Default Tunnel', 'The marked default route is chosen far more often despite equal alternatives.', 'Review every route explicitly', 'Separate evidence from the default.', 'Stay with the mark', 'Assume default means recommended.', 'Status quo bias makes inaction and defaults unusually influential.'],
  ['escalation', '🧱', 'One More Support Beam', 'A failing tunnel has consumed half the budget and requests still more.', 'Reassess future value from zero', 'Ignore unrecoverable spending.', 'Fund it to justify the past', 'Protect what has already been spent.', 'Escalation of commitment turns sunk costs into reasons for further investment.'],
  ['explore-exploit', '🗺️', 'Known Vein or New Shaft', 'A known vein pays steadily; unexplored shafts might be richer.', 'Reserve some effort for exploration', 'Balance learning with current reward.', 'Mine only the known vein', 'Maximize today’s predictable yield.', 'The explore–exploit dilemma values information that improves later choices.'],
  ['bandit', '🎰', 'Three Rusted Levers', 'Each lever has an unknown payout rate learned only by pulling it.', 'Test, then favor strong evidence', 'Update while preserving limited exploration.', 'Commit after one win', 'Treat the first result as decisive.', 'Multi-armed bandits require learning and earning at the same time.'],
  ['stopping-chests', '📦', 'The Row of Chests', 'You may open chests in order but cannot return after taking one.', 'Set a sample period', 'Use early chests to establish a threshold.', 'Take the first nonempty chest', 'Avoid ever passing a prize.', 'Optimal stopping sacrifices early options to learn what later quality means.'],
  ['secretary-torch', '🕯️', 'The Torchbearer Trial', 'Applicants arrive once in random order; only the best matters.', 'Observe about 37%, then take the next record', 'Use the classic stopping threshold.', 'Choose the final applicant', 'Collect maximum information first.', 'The 1/e rule balances sampling against the shrinking opportunity to choose.'],
  ['overgrazed-moss', '🌿', 'The Overgrazed Moss', 'Each camp gains from harvesting more glow-moss while regrowth is shared.', 'Set and enforce a quota', 'Align private harvest with renewal.', 'Harvest before others do', 'Race to capture the remaining stock.', 'Open access can produce a race that depletes a resource everyone values.'],
  ['bystander', '🚨', 'The Distant Cry', 'Many delvers hear a cry, so each assumes someone else will respond.', 'Name yourself as responder', 'Break diffusion of responsibility.', 'Wait for a better rescuer', 'Assume the crowd guarantees help.', 'Responsibility can diffuse as group size grows.'],
  ['hawk-dove', '🦅', 'Hawk and Dove at the Cache', 'Aggression wins against restraint but mutual aggression is ruinous.', 'Mix firmness with restraint', 'Avoid becoming predictably exploitable.', 'Always attack', 'Claim every uncontested cache.', 'Hawk–Dove equilibria balance the gain from aggression against collision costs.'],
  ['battle-sexes', '🎭', 'Forge or Archive', 'Two partners want to stay together but prefer different destinations.', 'Alternate or randomize fairly', 'Preserve coordination while sharing preference costs.', 'Go to your own favorite', 'Hope the other always yields.', 'Coordination has value even when players disagree over which equilibrium is best.'],
  ['network-effect', '📡', 'The Whispering Runes', 'A communication rune becomes more valuable as more delvers use the same kind.', 'Coordinate on a compatible standard', 'Capture the network benefit.', 'Choose an isolated superior rune', 'Optimize only standalone quality.', 'Network effects can make compatibility more valuable than individual product quality.'],
  ['principal-agent', '📋', 'The Absent Mine Owner', 'An owner pays a foreman whose effort is difficult to observe.', 'Reward measurable outcomes carefully', 'Align incentives while guarding against gaming.', 'Pay only a fixed wage', 'Assume effort cannot change.', 'Principal–agent problems arise when goals differ and actions are hidden.'],
];

function makeQuiz(entry, index) {
  const [id, emoji, title, text, correct, wrongA, wrongB, explanation] = entry;
  return [id, {
    emoji, title, text, extra: true, explanation,
    choices: [
      { key: 'correct', label: correct, desc: 'Commit to this answer.', outcome: 'correct', gold: 35 + (index % 5) * 5 },
      { key: 'wrong-a', label: wrongA, desc: 'Commit to this answer.', outcome: 'wrong', damage: 4 + (index % 4) },
      { key: 'wrong-b', label: wrongB, desc: 'Commit to this answer.', outcome: 'wrong', damage: 4 + (index % 4) },
    ],
  }];
}

function makeDilemma(entry, index) {
  const [id, emoji, title, text, prudent, prudentDesc, risky, riskyDesc, explanation] = entry;
  return [id, {
    emoji, title, text, extra: true, explanation,
    choices: [
      { key: 'prudent', label: prudent, desc: prudentDesc, outcome: 'prudent', gold: 25 + (index % 4) * 5 },
      { key: 'risk', label: risky, desc: riskyDesc, outcome: 'risk', chance: .38 + (index % 3) * .08, gold: 65 + (index % 4) * 10, damage: 7 + (index % 5) },
      { key: 'leave', label: 'Leave the chamber', desc: 'Take no prize and recover your breath.', outcome: 'leave', heal: 4 + (index % 4) },
    ],
  }];
}

export const EXTRA_EVENT_CATALOG = Object.fromEntries([
  ...QUIZZES.map(makeQuiz),
  ...DILEMMAS.map(makeDilemma),
]);

